# These parameters are the Planck cosmological parameters
H_0 :  67.74
Omega_M : 0.3089
Omega_L : 0.6911
Omega_bh2 : 0.02230
Omega_ch2 : 0.1188
Omega_k : 0.0
n_s : 0.9667
sigma_8 : 0.8159
tau : 0.066

# Parameters concerning the output power spectrum
z : 0.57
k_min : 0.0001
k_max : 10
num_points : 2000

# Output file name
outFile : camb_matterpower_z0.57.dat
